- Set default number of nodes for each topology - Disabled relay logs in all topologies - Changed method of finding the master, as a result of disabling relay logs - Fixed installation error. Errors from sb_make_sandboxes were not detected.

diff --git a/tungsten-sandbox3/sb_make_sandboxes b/tungsten-sandbox3/sb_make_sandboxes
--- a/tungsten-sandbox3/sb_make_sandboxes
+++ b/tungsten-sandbox3/sb_make_sandboxes
@@ -3,6 +3,14 @@ sandboxdir=$(dirname $0)
 . $sandboxdir/sb_vars.sh
 . $sandboxdir/sb_common.sh
 
+
+if [ $HOW_MANY_NODES -lt 2 ]
+then
+    grep HOW_MANY_NODES $sandboxdir/sb_vars.sh
+    echo "Can't create a multiple sandbox with less than 2 nodes"
+    exit 1
+fi
+
 SANDBOX_BINARY=$HOME/opt/mysql
 TARGET=$1
 if [ -n "$TARGET" ] 
