- Fixed issue in sb_test_sandbox when determining the master database port - Fixed issue in sb_test_all_topologies. It will now exit if a failure occurs. - Added variables to test various failures

diff --git a/tungsten-sandbox3/sb_test_all_topologies b/tungsten-sandbox3/sb_test_all_topologies
--- a/tungsten-sandbox3/sb_test_all_topologies
+++ b/tungsten-sandbox3/sb_test_all_topologies
@@ -73,6 +73,12 @@ do
     # $sandboxdir/sb_$topology > installation.log 2>&1
     exit_code=$?
     unset TEST_ALL_TOPOLOGIES
+    if [ -n "$TEST_INSTALLATION_FAILURE" -a "$exit_code" == "0" ]
+    then
+        echo "Testing installation failure"
+        echo "Installation succeeded, but we are simulating a failure"
+        exit_code=111
+    fi
     if [ "$exit_code" != "0" ]
     then
         UNEXPLAINED=$(grep 'At least one replication service has experienced an error' installation.log)
@@ -84,17 +90,29 @@ do
         exit $exit_code
     fi
     rm -f testing.log
-    $TUNGSTEN_SB/sb_test_sandbox | tee testing.log
+    $TUNGSTEN_SB/sb_test_sandbox >> testing.log 2>&1
     exit_code=$?
     pass=$(grep '^ok' testing.log | wc -l)
     fail=$(grep '^not ok' testing.log | wc -l)
+    fail=$(($fail+0))
+    pass=$(($pass+0))
     tests=$(($pass+$fail))
     total_pass=$(($total_pass+$pass))
     total_fail=$(($total_fail+$fail))
     total_tests=$(($total_tests+$tests))
     if [ "$exit_code" != "0" ]
     then
+        cat testing.log
+        echo "exit code: <$exit_code>"
         exit $exit_code
+    fi
+    # echo "pass:<$pass>"
+    # echo "fail:<$fail>"
+    cat testing.log
+    if [ "$fail" != "0" ]
+    then
+        echo "<$fail> failures detected"
+        exit 1
     fi
     echo "# Cleaning up ..."
     $TUNGSTEN_SB/sb_erase_sandbox > uninstall.log 2>&1
diff --git a/tungsten-sandbox3/sb_test_sandbox b/tungsten-sandbox3/sb_test_sandbox
--- a/tungsten-sandbox3/sb_test_sandbox
+++ b/tungsten-sandbox3/sb_test_sandbox
@@ -225,12 +225,48 @@ do
     role=$(echo $SERVICE_MASTER | tr ',' ' '| awk '{print $3}')
     # db_port=$(echo $pipeline | perl -nle 'print $1 if m{^jdbc:\w+:[^:]+://[^:]+:(\d+)}')
 
-    extractor_db_port=$($TREPCTL -port $rmiport -service $service properties -filter replicator.extractor.dbms.port | perl -nle 'print $1 if /"(\d+)"}?$/')
+    extractor_db_port=$($TREPCTL -port $rmiport -service $service properties -filter replicator.global.extract.db.port | perl -nle 'print $1 if /"(\d+)"}?$/')
+    if [ -z "$extractor_db_port" ]
+    then
+        echo "error retrieving the extractor port"
+        exit 1
+    fi
     applier_db_port=$($TREPCTL -port $rmiport -service $service properties -filter replicator.applier.dbms.port | perl -nle 'print $1 if /"(\d+)"}?$/')
+    if [ -z "$applier_db_port" ]
+    then
+        applier_db_port=$($TREPCTL -port $rmiport -service $service properties -filter replicator.datasource.global.connectionSpec.port | perl -nle 'print $1 if /"(\d+)"}?$/')
+    fi
+    if [ -z "$applier_db_port" ]
+    then
+        echo "error retrieving the applier port"
+        exit 1
+    fi
     db_port=$($TREPCTL -port $rmiport -service $service properties -filter replicator.global.db.port | perl -nle 'print $1 if /"(\d+)"}?$/')
+    if [ -z "$db_port" ]
+    then
+        db_port=$($TREPCTL -port $rmiport -service $service properties -filter replicator.datasource.global.connectionSpec.port | perl -nle 'print $1 if /"(\d+)"}?$/')
+    fi
+    if [ -z "$db_port" ]
+    then
+        echo "error retrieving the global db port"
+        exit 1
+    fi
     if [ "$extractor_db_port" != "$applier_db_port" ]
     then
         db_port=$extractor_db_port
+    fi
+    if [ -n "$TEST_EXIT_CODE" ]
+    then
+        echo "Testing exit code <$TEST_EXIT_CODE>"
+        exit $TEST_EXIT_CODE
+    fi
+    if [ -n "$TEST_FAILURE_NUM" ]
+    then
+        echo "ok - fake pass for testing"
+        echo "not ok - fake failure for testing"
+        echo "ok - another fake pass for testing"
+        echo "not ok - more fake failure for testing"
+        exit 0
     fi
     #echo "master service $service"
     #echo "master rmiport $rmiport"
