- Fixed check in load data with parallel replication (thanks Csaba E. Simon) - improved output of multi_trepctl by adding aliases - improved test_cluster with a check for Issue#821 - partial refactoring by centralizing functions in utilities.sh

diff --git a/trunk/cookbook/load_data b/trunk/cookbook/load_data
--- a/trunk/cookbook/load_data
+++ b/trunk/cookbook/load_data
@@ -69,6 +69,7 @@ fill_roles
 JOB_INFO_PATH=$TUNGSTEN_BASE/tungsten/load
 
 CHECKSUM_DBS=()
+[[ $LOAD_TEST_OPTIONS =~ --instances=([0-9]*) ]] && INSTANCES=${BASH_REMATCH[1]} || INSTANCES=1
 
 for HOST in  ${MASTERS[*]}
 do
@@ -100,6 +101,16 @@ do
     then
         CHECKSUM_DBS[$COUNTER]=$db
         COUNTER=$(($COUNTER+1))
+        if [ "$INSTANCES" -gt "1" ]
+        then
+            for N in $(seq 1 $INSTANCES); do
+                CHECKSUM_DBS[$COUNTER]=$db$N
+                    COUNTER=$(($COUNTER+1))
+            done
+        else
+            CHECKSUM_DBS[$COUNTER]=$db
+            COUNTER=$(($COUNTER+1))
+        fi
     fi
     V=''
     [ -n "$VERBOSE" ] && [ "$OPERATION" == "stop" ] && V='--verbose'
@@ -123,23 +134,53 @@ done
 function check_contents
 {
     echo ""
+    [ -z "$TESTS" ]  && TESTS=0
+    [ -z "$PASSED" ] && PASSED=0
+    [ -z "$FAILED" ] && FAILED=0
     for DB in ${CHECKSUM_DBS[*]}
     do
+        FIRST_COUNT=''
         for HOST in ${ALL_NODES[*]}
         do
-            echo -n "# COUNT host $HOST - $DB - "
-            $MYSQL -h $HOST -BN -e "select count(*) from $DB.tbl3"
+            echo -n "# COUNT host $HOST - db: $DB - "
+            COUNT=$($MYSQL -h $HOST -BN -e "select count(*) from $DB.tbl3")
+            echo $COUNT
+            if [ -n "$FIRST_COUNT" ]
+            then
+                ok_equal $COUNT $FIRST_COUNT "Count in $HOST matches"
+            else
+                FIRST_COUNT=$COUNT
+            fi
         done
     done
 
     for DB in ${CHECKSUM_DBS[*]}
     do
+        FIRST_CRC=''
         for HOST in ${ALL_NODES[*]}
         do
             echo -n "# CRC host $HOST - "
-            $MYSQL -h $HOST -BN -e "checksum table $DB.tbl3"
+            CRC=$($MYSQL -h $HOST -BN -e "checksum table $DB.tbl3" | awk '{print $2}')
+            echo $CRC
+            if [ -n "$FIRST_CRC" ]
+            then
+                ok_equal $CRC $FIRST_CRC "CRC in $HOST matches"
+            else
+                FIRST_CRC=$CRC
+            fi
         done
     done
+    #
+    PASSED_PERCENTAGE=$(ruby -e 'print eval(ARGV[0])' "$PASSED.0/$TESTS.0*100" )
+    FAILED_PERCENTAGE=$(ruby -e 'print eval(ARGV[0])' "$FAILED.0/$TESTS.0*100" )
+
+    echo $DASHLINE
+    echo "# --- provisional tally --- "
+    printf "# passed: %4d (%6.2f%%)\n" $PASSED $PASSED_PERCENTAGE
+    printf "# failed: %4d (%6.2f%%)\n" $FAILED $FAILED_PERCENTAGE
+    echo $DASHLINE
+    echo ""
+    [ "$FAILED" != "0" ] && exit $FAILED
 }
 
 case "$OPERATION" in
diff --git a/trunk/cookbook/test_cluster b/trunk/cookbook/test_cluster
--- a/trunk/cookbook/test_cluster
+++ b/trunk/cookbook/test_cluster
@@ -71,45 +71,6 @@ TESTS=0
 PASSED=0
 FAILED=0
 
-function ok_equal
-{
-    fact=$1
-    expected=$2
-    msg=$3
-    # echo "++ <$1> <$2> <$3>"
-    if [ "$fact" == "$expected" ]
-    then
-        echo -n "ok"
-        PASSED=$(($PASSED+1))
-    else
-        echo -n "not ok"
-        FAILED=$(($FAILED+1))
-        msg="$msg (found: <$fact> - expected: <$expected>)"
-    fi
-    TESTS=$(($TESTS+1))
-    TEST_N=$(printf "%05d" $TESTS)
-    TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
-    echo " - ($TEST_N) [$TIMESTAMP] $msg"
-}
-
-
-function ok_greater
-{
-    fact=$1
-    expected=$2
-    msg=$3
-    if [ $fact -ge $expected ]
-    then
-        echo -n "ok"
-        PASSED=$(($PASSED+1))
-    else
-        echo -n "not ok"
-        FAILED=$(($FAILED+1))
-    fi
-    echo " - $msg"
-    TESTS=$(($TESTS+1))
-}
-
 function check_security_status
 {
     for NODE in ${ALL_NODES[*]}
@@ -391,6 +352,13 @@ do
         check_for_table "test" "t$COUNT" 0 $NODE
         check_for_table "test" "boundaries$COUNT" 0 $NODE
         $MYSQL -h $NODE -e "drop table if exists test.v$COUNT"
+        $MYSQL -h $NODE -e "drop table if exists test.test_sql_mode$COUNT"
+        $MYSQL -h $NODE -e "create table test.test_sql_mode$COUNT(i int)"
+        
+        # This is a test for ISSUE#821
+        # Replication will fail if this issue has a regression
+        $MYSQL -h $NODE -e "set sql_mode=STRICT_ALL_TABLES;set binlog_format=row;insert into test.test_sql_mode$COUNT values (1)"
+        # 
         $MYSQL -h $NODE -e "create table test.t$COUNT(id int not null primary key, c char(20), b blob, t text, ti time$DDL_POSTFIX, d date, dt datetime$DDL_POSTFIX, ts timestamp$DDL_POSTFIX, f double(20,15), e enum ('one', 'two', 'three'), s set ('yellow','red', 'white','blue')) engine=innodb"
         $MYSQL -h $NODE -e "create table test.tu$COUNT(id int not null primary key, c char(20), t tinyint, ut tinyint unsigned, s smallint, us smallint unsigned, m mediumint, um mediumint unsigned, i int, ui int unsigned, b bigint, ub bigint unsigned ) engine=innodb"
         $MYSQL -h $NODE -e "create or replace view test.v$COUNT as select * from test.t$COUNT"
@@ -398,10 +366,10 @@ do
 
         check_for_table "test" "t$COUNT" 1 $NODE
         check_for_table "test" "boundaries$COUNT" 1 $NODE
-        $MYSQL -h $NODE -e "insert into test.boundaries$COUNT values (1, 'inserted by node #$COUNT', null, null, null, null)"
-        $MYSQL -h $NODE -e "insert into test.boundaries$COUNT values (2, 'inserted by node #$COUNT', '0', '0', '0', '0')"
-        $MYSQL -h $NODE -e "insert into test.boundaries$COUNT values (3, 'inserted by node #$COUNT', '$MIN_TIME', '$MIN_D', '$MIN_DT', '$MIN_TS')"
-        $MYSQL -h $NODE -e "insert into test.boundaries$COUNT values (4, 'inserted by node #$COUNT', '$MAX_TIME', '$MAX_D', '$MAX_DT', '$MAX_TS')"
+        $MYSQL -h $NODE -e "set sql_mode=''; insert into test.boundaries$COUNT values (1, 'inserted by node #$COUNT', null, null, null, null)"
+        $MYSQL -h $NODE -e "set sql_mode=''; insert into test.boundaries$COUNT values (2, 'inserted by node #$COUNT', '0', '0', '0', '0')"
+        $MYSQL -h $NODE -e "set sql_mode=''; insert into test.boundaries$COUNT values (3, 'inserted by node #$COUNT', '$MIN_TIME', '$MIN_D', '$MIN_DT', '$MIN_TS')"
+        $MYSQL -h $NODE -e "set sql_mode=''; insert into test.boundaries$COUNT values (4, 'inserted by node #$COUNT', '$MAX_TIME', '$MAX_D', '$MAX_DT', '$MAX_TS')"
         $MYSQL -h $NODE -e "insert into test.v$COUNT values (1, 'inserted by node #$COUNT', '$SAMPLE_BLOB', '$SAMPLE_T', '$SAMPLE_TIME', '$SAMPLE_D', '$SAMPLE_DT', '$SAMPLE_TS', $SAMPLE_F,'$SAMPLE_ENUM', '$SAMPLE_SET')"
         $MYSQL -h $NODE -e "insert into test.tu$COUNT values (1, 'inserted by node #$COUNT', $SAMPLE_TINYINT, $SAMPLE_U_TINYINT, $SAMPLE_SMALLINT, $SAMPLE_U_SMALLINT, $SAMPLE_MEDIUMINT, $SAMPLE_U_MEDIUMINT, $SAMPLE_INT,$SAMPLE_U_INT, $SAMPLE_BIGINT, $SAMPLE_U_BIGINT)"
         check_for_records "test" "t$COUNT" 1 $NODE
@@ -497,6 +465,21 @@ done  # iter
 
 check_if_replicators_are_running 'After tests'
 check_security_status
+
+if [ -f $cookbook_dir/data_loading ]
+then
+    if [ -n "$CHECK_CONTENTS" ]
+    then
+        $cookbook_dir/load_data stop
+        exit_code=$?
+        if [ "$exit_code" != "0" ]
+        then
+            FAILED=$(($FAILED+$exit_code))
+            TESTS=$(($TESTS+$exit_code))
+        fi
+    fi
+fi
+
 #
 PASSED_PERCENTAGE=$(ruby -e 'print eval(ARGV[0])' "$PASSED.0/$TESTS.0*100" )
 FAILED_PERCENTAGE=$(ruby -e 'print eval(ARGV[0])' "$FAILED.0/$TESTS.0*100" )
