Add testing to support Issue 558 : Add support for MySQL 5.6 row replication format changes
The script test_cluster now tests several data types, checking the exact return values for every slave

diff --git a/trunk/cookbook/test_cluster b/trunk/cookbook/test_cluster
--- a/trunk/cookbook/test_cluster
+++ b/trunk/cookbook/test_cluster
@@ -71,6 +71,7 @@ function ok_equal
     fact=$1
     expected=$2
     msg=$3
+    # echo "++ <$1> <$2> <$3>"
     if [ "$fact" == "$expected" ]
     then
         echo -n "ok"
@@ -97,15 +98,43 @@ function ok_greater
     TESTS=$((TESTS+1))
 }
 
+DATA_POSTFIX=''
+DDL_POSTFIX=''
+MYSQL_VERSION=$($MYSQL -h ${MASTERS[0]} -BN -e 'select @@version'| perl -lne 'print $1 if /(\d+\.\d+)/')
+if [ -z "$MYSQL_VERSION" ]
+then
+    echo "error detecting MySQL version"
+    exit 1
+fi
+if [ "$MYSQL_VERSION" == "5.7" ]
+then
+    MYSQL_VERSION='5.6'
+fi
+
+if [ "$MYSQL_VERSION" == "5.6" ]
+then
+    DATA_POSTFIX='.0123'
+    DDL_POSTFIX='(4)'
+fi
+
+SAMPLE_BLOB=abc
+SAMPLE_T=xyz
+SAMPLE_D=1969-09-01
+SAMPLE_DT="2003-04-26 09:15:57$DATA_POSTFIX"
+SAMPLE_TS="2003-04-26 09:15:58$DATA_POSTFIX"
 
 for NODE in ${MASTERS[*]} 
 do 
     COUNT=$(($COUNT+1))
+    if [ -n "$BINLOG_FORMAT" ]
+    then
+        $MYSQL -h $NODE -e "set global binlog_format=$BINLOG_FORMAT"
+    fi
     $MYSQL -h $NODE -e "drop table if exists test.t$COUNT"
     $MYSQL -h $NODE -e "drop table if exists test.v$COUNT"
-    $MYSQL -h $NODE -e "create table test.t$COUNT(id int not null primary key, c char(20)) engine=innodb"
+    $MYSQL -h $NODE -e "create table test.t$COUNT(id int not null primary key, c char(20), b blob, t text, d date, dt datetime$DDL_POSTFIX, ts timestamp$DDL_POSTFIX) engine=innodb"
     $MYSQL -h $NODE -e "create or replace view test.v$COUNT as select * from test.t$COUNT"
-    $MYSQL -h $NODE -e "insert into test.v$COUNT values (1, 'inserted by node #$COUNT')"
+    $MYSQL -h $NODE -e "insert into test.v$COUNT values (1, 'inserted by node #$COUNT', '$SAMPLE_BLOB', '$SAMPLE_T', '$SAMPLE_D', '$SAMPLE_DT', '$SAMPLE_TS')"
     HOW_MANY_SERVICES=$($TREPCTL -host $NODE services | grep role | grep master| wc -l)
     # echo "#M> $HOW_MANY_SERVICES"
     ok_greater $HOW_MANY_SERVICES $EXPECTED_SERVICES_MASTER "Master $NODE has at least $EXPECTED_SERVICES_MASTER master services"
@@ -125,6 +154,7 @@ do
 done
 
 sleep 2
+# set -x
 for SLAVE in ${SLAVES[*]} 
 do
     echo "# slave: $SLAVE"
@@ -135,9 +165,19 @@ do
         TABLE_COUNT=$($MYSQL -BN -h $NODE -e "select count(*) from information_schema.tables where table_schema='test' and  table_name = 't$COUNT'")
         VIEW_COUNT=$($MYSQL -BN -h $NODE -e "select count(*) from information_schema.tables where table_schema='test' and  table_name = 'v$COUNT'")
         RECORD_COUNT=$($MYSQL -BN -h $NODE -e "select count(*) from test.t$COUNT where c = 'inserted by node #$COUNT' ")
+        BLOB_CONTENT=$($MYSQL -BN -h $NODE -e "select b from test.t$COUNT where c = 'inserted by node #$COUNT' ")
+        TEXT_CONTENT=$($MYSQL -BN -h $NODE -e "select t from test.t$COUNT where c = 'inserted by node #$COUNT' ")
+        DATE_CONTENT=$($MYSQL -BN -h $NODE -e "select d from test.t$COUNT where c = 'inserted by node #$COUNT' ")
+        DT_CONTENT=$($MYSQL -BN -h $NODE -e "select dt from test.t$COUNT where c = 'inserted by node #$COUNT' ")
+        TS_CONTENT=$($MYSQL -BN -h $NODE -e "select ts from test.t$COUNT where c = 'inserted by node #$COUNT' ")
         ok_equal $TABLE_COUNT 1 "Tables from master #$COUNT"
         ok_equal $VIEW_COUNT 1 "Views from master #$COUNT"
-        ok_equal $RECORD_COUNT 1 "Records from master #$COUNT"
+        ok_equal $RECORD_COUNT 1 "Records from master #$COUNT : <$RECORD_COUNT>"
+        ok_equal $BLOB_CONTENT "$SAMPLE_BLOB" "Blob from master #$COUNT : <$BLOB_CONTENT>"
+        ok_equal $TEXT_CONTENT "$SAMPLE_T" "Text from master #$COUNT : <$TEXT_CONTENT>"
+        ok_equal $DATE_CONTENT "$SAMPLE_D" "Date from master #$COUNT : <$DATE_CONTENT>"
+        ok_equal "$DT_CONTENT" "$SAMPLE_DT" "Datetime from master #$COUNT : <$DT_CONTENT>"
+        ok_equal "$TS_CONTENT" "$SAMPLE_TS" "Timestamp from master #$COUNT : <$TS_CONTENT>"
         # $MYSQL -h $NODE -e "select * from test.t$COUNT"
     done
     HOW_MANY_SERVICES=$($TREPCTL -host $SLAVE services | grep role | grep slave| wc -l)
