Updated installation recipes with new options --masters and --slaves. (Issue#623)
Implemented Issue#640

1) deploy_to_sandboxes was renamed to deploy_sandboxes
2) When sandboxes are created, the following happens:
   a) we take a copy of USER_VALUES.sh and USER_VALUES.local.sh
   b) we create a script ./cookbook/remove_sandboxes, which can remove the sandboxes created by deploy_sandboxes
   c) we also create a script ./cookbook/restore_user_values, which copies back the saved files in stead of the ones with sandboxes credentials.
3) There is a shortcut ./cookbook/db_use which is created regardless of the kind of server we are using.
   To use this shortcut properly, you must specify the host:
   ./cookbook/db_use -h host4
   (Notice that, due to the way sandboxes are installed, you can't use 'localhost' [unless you also specify the socket], but you should use 127.0.0.1)

diff --git a/trunk/cookbook/test_all_topologies b/trunk/cookbook/test_all_topologies
--- a/trunk/cookbook/test_all_topologies
+++ b/trunk/cookbook/test_all_topologies
@@ -71,16 +71,31 @@ function test_one_topology
 {
     TOPOLOGY=$1
     METHOD=$2
+    MYSQL_VERSION=$($MYSQL -h ${MASTERS[0]} -BN -e 'select @@version'| perl -lne 'print $1 if /(\d+\.\d+)/')
+    if [ -z "$MYSQL_VERSION" ]
+    then
+        echo "error detecting MySQL version"
+        exit 1
+    fi
+
     if [ -n "$TEST_UNDER_LOAD" ]
     then
         $cookbook_dir/load_data >> $INSTALL_LOG
     fi
-    for MODE in statement row mixed 
+    formats=(statement row mixed)
+    if [ "$MYSQL_VERSION" != "5.0" ]
+    then
+        formats=(statement)
+    fi
+    for MODE in ${formats[*]}
     do
-        for MASTER in ${MASTERS[*]}
-        do
-            $MYSQL -h $MASTER -e "set global binlog_format=$MODE"
-        done 
+        if [ "$MYSQL_VERSION" != "5.0" ]
+        then
+            for MASTER in ${MASTERS[*]}
+            do
+                $MYSQL -h $MASTER -e "set global binlog_format=$MODE"
+            done 
+        fi
         echo "# testing with binlog_format=$MODE" >> /tmp/test_log$$ 
         echo "# testing with binlog_format=$MODE" 
         $cookbook_dir/show_cluster 
