- modified the way we call load-data in a star topology (hub is now excluded) - changed 'test_all_topologies' to be more modular - made call to heartbeat in show_cluster depending on a variable

diff --git a/trunk/cookbook/test_all_topologies b/trunk/cookbook/test_all_topologies
--- a/trunk/cookbook/test_all_topologies
+++ b/trunk/cookbook/test_all_topologies
@@ -20,83 +20,107 @@ echo "# `date`" > $TEST_LOG
 
 exportVERBOSE=1
 exit_code=0
+
+
+function install_topology
+{
+    TOPOLOGY=$1
+    METHOD=$2
+    if [ "$METHOD" == "tpm" ]
+    then
+        export USE_TPM=1
+        rm -f deploy.cfg*
+    else
+        unset USE_TPM
+    fi
+    echo "# $TOPOLOGY (using $METHOD)" 
+    echo "# $TOPOLOGY" >> $INSTALL_LOG
+    echo "# $TOPOLOGY" >> $TEST_LOG
+    UCTOPOLOGY=$(perl -e "print uc '$TOPOLOGY'")
+    $cookbook_dir/install_$TOPOLOGY >> $INSTALL_LOG 
+    exit_code=$?
+    if [ "$exit_code" != "0" ]
+    then
+        echo "# ERROR installing $TOPOLOGY (using $METHOD)"
+        cat $INSTALL_LOG
+        exit $exit_code
+    fi
+    if [ -f /tmp/test_log$$ ] ; then rm /tmp/test_log$$ ; fi
+    . $cookbook_dir/BOOTSTRAP.sh NODES_$UCTOPOLOGY.sh
+}
+
+function uninstall_topology
+{
+    export I_WANT_TO_UNINSTALL=1
+    export STOP_REPLICATORS=1
+    export REMOVE_TUNGSTEN_BASE=1
+    export REMOVE_SERVICE_SCHEMA=1
+    export REMOVE_TEST_SCHEMAS=1
+    export CLEAN_NODE_DATABASE_SERVER=1
+    $cookbook_dir/clear_cluster >> $INSTALL_LOG
+    unset I_WANT_TO_UNINSTALL
+    if [ -n "$KILL_JAVA_PROCESS" ]
+    then
+        # Making sure that all the remaining processes are removed
+        pkill -9 wrapper
+        pkill -9 java 
+    fi
+}
+
+function test_one_topology
+{
+    TOPOLOGY=$1
+    METHOD=$2
+    if [ -n "$TEST_UNDER_LOAD" ]
+    then
+        $cookbook_dir/load_data >> $INSTALL_LOG
+    fi
+    for MODE in statement row mixed 
+    do
+        for MASTER in ${MASTERS[*]}
+        do
+            $MYSQL -h $MASTER -e "set global binlog_format=$MODE"
+        done 
+        echo "# testing with binlog_format=$MODE" >> /tmp/test_log$$ 
+        echo "# testing with binlog_format=$MODE" 
+        $cookbook_dir/show_cluster 
+        $cookbook_dir/show_cluster >> $INSTALL_LOG
+        ##############################################
+        $cookbook_dir/test_cluster >> /tmp/test_log$$
+        exit_code=$?
+        if [ "$exit_code" != "0" ]
+        then
+            echo "# ERROR testing $TOPOLOGY (using $METHOD)"
+            cat /tmp/test_log$$
+            exit $exit_code
+        fi
+        ##############################################
+        $cookbook_dir/show_cluster 
+        $cookbook_dir/show_cluster >> $INSTALL_LOG
+        cat /tmp/test_log$$ >> $TEST_LOG
+    done
+    if [ -n "$TEST_UNDER_LOAD" ]
+    then
+        SAVE_TEST_OPTIONS=$LOAD_TEST_OPTIONS
+        export LOAD_TEST_OPTIONS="$LOAD_TEST_OPTIONS --remove=all"
+        $cookbook_dir/load_data stop >> $INSTALL_LOG
+        export LOAD_TEST_OPTIONS=$SAVE_TEST_OPTIONS
+    fi
+
+    cat /tmp/test_log$$
+    rm /tmp/test_log$$
+}
+
+
 for TOPOLOGY in master_slave fan_in all_masters star 
 do
     for METHOD in tungsten_installer tpm
     do
-        if [ "$METHOD" == "tpm" ]
-        then
-            export USE_TPM=1
-            rm -f deploy.cfg*
-        else
-            unset USE_TPM
-        fi
-        echo "# $TOPOLOGY (using $METHOD)" 
-        echo "# $TOPOLOGY" >> $INSTALL_LOG
-        echo "# $TOPOLOGY" >> $TEST_LOG
-        UCTOPOLOGY=$(perl -e "print uc '$TOPOLOGY'")
-        $cookbook_dir/install_$TOPOLOGY >> $INSTALL_LOG 
-        exit_code=$?
-        if [ "$exit_code" != "0" ]
-        then
-            echo "# ERROR installing $TOPOLOGY (using $METHOD)"
-            cat $INSTALL_LOG
-            exit $exit_code
-        fi
-        if [ -f /tmp/test_log$$ ] ; then rm /tmp/test_log$$ ; fi
-        . $cookbook_dir/BOOTSTRAP.sh NODES_$UCTOPOLOGY.sh
-        if [ -n "$TEST_UNDER_LOAD" ]
-        then
-            $cookbook_dir/load_data >> $INSTALL_LOG
-        fi
-        for MODE in statement mixed  row
-        do
-            for MASTER in ${MASTERS[*]}
-            do
-                $MYSQL -h $MASTER -e "set global binlog_format=$MODE"
-            done 
-            echo "# testing with binlog_format=$MODE" >> /tmp/test_log$$ 
-            echo "# testing with binlog_format=$MODE" 
-            $cookbook_dir/show_cluster 
-            $cookbook_dir/show_cluster >> $INSTALL_LOG
-            ##############################################
-            $cookbook_dir/test_cluster >> /tmp/test_log$$
-            exit_code=$?
-            if [ "$exit_code" != "0" ]
-            then
-                echo "# ERROR testing $TOPOLOGY (using $METHOD)"
-                cat /tmp/test_log$$
-                exit $exit_code
-            fi
-            ##############################################
-            $cookbook_dir/show_cluster 
-            $cookbook_dir/show_cluster >> $INSTALL_LOG
-            cat /tmp/test_log$$ >> $TEST_LOG
-        done
-        if [ -n "$TEST_UNDER_LOAD" ]
-        then
-            SAVE_TEST_OPTIONS=$LOAD_TEST_OPTIONS
-            export LOAD_TEST_OPTIONS="$LOAD_TEST_OPTIONS --remove=all"
-            $cookbook_dir/load_data stop >> $INSTALL_LOG
-            export LOAD_TEST_OPTIONS=$SAVE_TEST_OPTIONS
-        fi
+        install_topology $TOPOLOGY $METHOD
 
-        cat /tmp/test_log$$
-        rm /tmp/test_log$$
-        export I_WANT_TO_UNINSTALL=1
-        export STOP_REPLICATORS=1
-        export REMOVE_TUNGSTEN_BASE=1
-        export REMOVE_SERVICE_SCHEMA=1
-        export REMOVE_TEST_SCHEMAS=1
-        export CLEAN_NODE_DATABASE_SERVER=1
-        $cookbook_dir/clear_cluster >> $INSTALL_LOG
-        unset I_WANT_TO_UNINSTALL
-        # Making sure that all the remaining processes are removed
-        if [ -n "$KILL_JAVA_PROCESS" ]
-        then
-            pkill -9 wrapper
-            pkill -9 java 
-        fi
+        test_one_topology $TOPOLOGY $METHOD
+        
+        uninstall_topology
     done
 done
 
