experimental support for tpm installation for master/slave and all-masters

diff --git a/trunk/cookbook/test_all_topologies b/trunk/cookbook/test_all_topologies
--- a/trunk/cookbook/test_all_topologies
+++ b/trunk/cookbook/test_all_topologies
@@ -20,35 +20,60 @@ echo "# `date`" > $TEST_LOG
 
 for TOPOLOGY in master_slave fan_in all_masters star
 do
-    echo "# $TOPOLOGY" 
-    echo "# $TOPOLOGY" >> $INSTALL_LOG
-    echo "# $TOPOLOGY" >> $TEST_LOG
-    UCTOPOLOGY=$(perl -e "print uc '$TOPOLOGY'")
-    $cookbook_dir/install_$TOPOLOGY >> $INSTALL_LOG 
-    if [ -f /tmp/test_log$$ ] ; then rm /tmp/test_log$$ ; fi
-    . $cookbook_dir/BOOTSTRAP.sh NODES_$UCTOPOLOGY.sh
-    for MODE in row statement
+    for METHOD in installer tpm
     do
-        for MASTER in ${MASTERS[*]}
+        skip=true
+        if [ "$TOPOLOGY" == "all_masters" -o "$TOPOLOGY" == "master_slave" -o "$METHOD" == "installer" ]
+        then
+            skip=false
+        fi
+        if [ "$skip" == "true" ]
+        then
+            break
+        fi
+        if [ "$METHOD" == "tpm" ]
+        then
+            export USE_TPM=1
+            rm -f deploy.cfg*
+        else
+            unset USE_TPM
+        fi
+        echo "# $TOPOLOGY (using $METHOD)" 
+        echo "# $TOPOLOGY" >> $INSTALL_LOG
+        echo "# $TOPOLOGY" >> $TEST_LOG
+        UCTOPOLOGY=$(perl -e "print uc '$TOPOLOGY'")
+        $cookbook_dir/install_$TOPOLOGY >> $INSTALL_LOG 
+        exit_code=$?
+        if [ "$exit_code" != "0" ]
+        then
+            echo "# ERROR installing $TOPOLOGY (using $METHOD)"
+            exit $exit_code
+        fi
+        if [ -f /tmp/test_log$$ ] ; then rm /tmp/test_log$$ ; fi
+        . $cookbook_dir/BOOTSTRAP.sh NODES_$UCTOPOLOGY.sh
+        for MODE in row statement
         do
-            $MYSQL -h $MASTER -e "set global binlog_format=$MODE"
-        done 
-        echo "# testing with binlog_format=$MODE" >> /tmp/test_log$$ 
-        # echo "# testing with binlog_format=$MODE" 
+            for MASTER in ${MASTERS[*]}
+            do
+                $MYSQL -h $MASTER -e "set global binlog_format=$MODE"
+            done 
+            echo "# testing with binlog_format=$MODE" >> /tmp/test_log$$ 
+            # echo "# testing with binlog_format=$MODE" 
 
-        $cookbook_dir/test_cluster >> /tmp/test_log$$
-        cat /tmp/test_log$$ >> $TEST_LOG
+            $cookbook_dir/test_cluster >> /tmp/test_log$$
+            cat /tmp/test_log$$ >> $TEST_LOG
+        done
+        cat /tmp/test_log$$
+        rm /tmp/test_log$$
+        export I_WANT_TO_UNINSTALL=1
+        export STOP_REPLICATORS=1
+        export REMOVE_TUNGSTEN_BASE=1
+        export REMOVE_SERVICE_SCHEMA=1
+        export REMOVE_TEST_SCHEMAS=1
+        export CLEAN_NODE_DATABASE_SERVER=1
+        $cookbook_dir/clear_cluster >> $INSTALL_LOG
+        unset I_WANT_TO_UNINSTALL
     done
-    cat /tmp/test_log$$
-    rm /tmp/test_log$$
-    export I_WANT_TO_UNINSTALL=1
-    export STOP_REPLICATORS=1
-    export REMOVE_TUNGSTEN_BASE=1
-    export REMOVE_SERVICE_SCHEMA=1
-    export REMOVE_TEST_SCHEMAS=1
-    export CLEAN_NODE_DATABASE_SERVER=1
-    $cookbook_dir/clear_cluster >> $INSTALL_LOG
-    unset I_WANT_TO_UNINSTALL
 done
 
 OK=$(grep "^ok" $TEST_LOG| wc -l)
