- Improved Issue#544 fix, by using a general purpose fill_roles function - The 'help' script could not run unless a cluster was installed. Fixed. - Add scripts   * insert_retrieve  node1 node2           Creates a table in node1 and retrieves it from node2   * tungsten_service {node|all} [service]  Shows the contents of trep_commit_seqno for a given node for all nodes. If 'service' is not given, it shows all   * query_node  node query                 runs a query in a given node   * query_all_nodes query                  runs a query in all nodes

diff --git a/cookbook/check_cookbook b/cookbook/check_cookbook
--- a/cookbook/check_cookbook
+++ b/cookbook/check_cookbook
@@ -5,6 +5,7 @@
 cd `dirname $0`
 
 MISSING=""
+UNDOCUMENTED=""
 for F in `cat MANIFEST` 
 do
     COMMENT=$(echo $F |grep '#')
@@ -19,18 +20,36 @@ do
             echo "not ok - $F not found"
             MISSING="$MISSING $F"
         fi
+        FOUND_IN_DOCS=$(grep $F REFERENCE.txt)
+        if [ -z "$FOUND_IN_DOCS" ]
+        then
+            echo "not ok - '$F' not described in the documentation"
+            UNDOCUMENTED="$UNDOCUMENTED $F"
+        fi
     fi
 done
 
+exit_code=0
 echo ""
 if [ -z "$MISSING" ]
 then
     echo "All files are accounted for"
 else
-    echo "*** WARNING"
-    echo "Missing files: $MISSING"
-    echo "****"
-    exit 1
+    echo "**** WARNING ****"
+    echo "** Missing files: $MISSING"
+    echo "*****************"
+    exit_code=1
 fi
 
+if [ -z "$UNDOCUMENTED" ]
+then
+    echo "All files are documented"
+else
+    echo "**** WARNING ****"
+    echo "Undocumented files: $UNDOCUMENTED"
+    echo "*****************"
+    exit_code=1
+fi
+
+exit $exit_code
 
