Fixed Issue 652:    installation of a fan-in cluster fails when fan-in slave is not last in the host list Fixed Issue 653:    Allow uninstall of tungsten-replicator to run in parallel Fixed Issue 654:    IP-detection procedure fails when host has multiple addresses
Fixed minor issues: 
- install_master_slave qith tpm was not using --reset (fixed)
- added nodes to template COMMON_NODES and NODES_* so it is easier to run clusters up to 8 nodes with minimal input
- added error checking to deploy_sandboxes

diff --git a/cookbook/deploy_sandboxes b/cookbook/deploy_sandboxes
--- a/cookbook/deploy_sandboxes
+++ b/cookbook/deploy_sandboxes
@@ -90,11 +90,21 @@ do
             ;;
         -P)
             export MYSQL_PORT=$2
+            if [ ! -d ~/opt/mysql/$MYSQL_VERSION ]
+            then
+                echo "Directory $MYSQL_VERSION not found in ~/opt/mysql"
+                exit 1
+            fi
             shift
             shift
             ;;
         -t)
             export TARBALL=$2
+            if [ ! -f $TARBALL ]
+            then
+                echo " file $TARBALL not found"
+                exit 1
+            fi
             shift
             shift
             ;;
@@ -110,6 +120,12 @@ do
     esac
 done
 
+
+if [ -n "$1" ]
+then
+    echo "unexpected argument '$1'"
+    show_help
+fi
 
 if [ -z "$NODES_LIST" ]
 then
@@ -162,6 +178,11 @@ do
    fi
    scp -p $BUILD_SB $HOST:$BUILD_SB
    ssh $HOST $BUILD_SB $SERVER_ID_COUNTER
+   if [ "$?" != "0" ]
+   then
+       echo "Error installing sandbox in node $HOST"
+       exit 1
+   fi
 done
 
 . $cookbook_dir/USER_VALUES.sh
